fixed issue123
mango-gremlin/arch-enemies pull request #166
Opened 2023-12-21 12:12 UTC by Raining-Cloud

## Motivation
closes #123 

## What was changed/added

Added a new group `animal_body` to the Area2D which already represents the body of the animal. By this we can check in the code if we have overlapping areas which also are a animal. This is done with a simple for loop in the drag_handler-

## Testing
Tested in multiple combinations which may cause aproblem

2023-12-21 21:36 UTC, marcel-iv requested changes
Works and doesn't seem to be causing bugs

However, the small segment of code (in the ``is_correct_placement`` function) is for some reason not inside the for loop, so we have two identical for loops, sequentially. The new if clause should simply be put inside the loop, if that doesn't cause any bugs.

 Also, please add a comment to your code, even though its fairly simple to understand.

2023-12-22 17:32 UTC, Raining-Cloud commented
> Works and doesn't seem to be causing bugs
> 
> However, the small segment of code (in the `is_correct_placement` function) is for some reason not inside the for loop, so we have two identical for loops, sequentially. The new if clause should simply be put inside the loop, if that doesn't cause any bugs.
> 
> Also, please add a comment to your code, even though its fairly simple to understand.

What kind of bugs? Due to I only added another return false option the Bug must be that the Animal cannot be placed in a certain spot. Otherwise its the general code causing problems. I don't get what you mean by the identically sequential loops?

2023-12-23 11:41 UTC, marcel-iv commented
![image](https://github.com/mango-gremlin/arch-enemies/assets/104799849/6b469c41-920c-4af2-82ef-fe709f0431e4)
I meant these two loops, however, I just realized that your loop checks for ``overlapping_areas``, while the already existing loop iterates over ``overlapping_bodies``. If this is necessary for your implementation, please feel free to accept and merge your PR.

Otherwise, everything looks great, thanks for adding the comment.

As previously mentioned, all bugs encountered while testing your code where there before, as covered in #123. Your approach seems robust, and easy to check for any bugs that we might have missed, which is great.

2023-12-24 00:15 UTC, marcel-iv approved these changes

2023-12-24 00:32 UTC, merged