Added basic overworld dialogue system
mango-gremlin/arch-enemies pull request #196
Opened 2023-12-27 22:46 UTC by DerSimi

This PR builds on #183,
it resolves #145 and soon #188

It is possible to create custom dialoges and add it to npcs.

For test reasons, every npc has the same, static dialogue.

The button listeners don't work although properly connected. Maybe there's something in the way, assistance is highly appreciated. So, for test reasons, the dialogue window buttons can be controlled using A, S, D

2023-12-27 23:44 UTC, ScatteredDrifter commented
Hi! 
Had a quick look and was able to work and observe your changes. 
However I've encountered the following issue ( not sure whether it was caused by me / my local repo? ) 

![image](https://github.com/mango-gremlin/arch-enemies/assets/63316422/2d23f311-a7d1-4e49-84a7-5c194f7789b0)

2023-12-28 10:05 UTC, DerSimi commented
should be fixed now, forgot to commit the background.

2024-01-03 20:58 UTC, mango-gremlin approved these changes
This looks and works amazing, and the implementation is really well organised and well documented, well done!!!

Sorry if i missed it -> is there also an option to make the dialogue recurring, in the sense that you can talk to an NPC several times with it saying the same thing?

Also I am not sure where the merge conflicts come from -> are these the same as for @ScatteredDrifter 's original branch?
And that branch was merged already, so we need to change this to merge into main, or is there another way?

2024-01-05 20:33 UTC, ScatteredDrifter requested changes
Thanks for your overhaul of the dialogue system. 
It works / looks great now, thanks a lot! 

I have some comments regarding the implementation: 

- Please don't write **questions or comments** into the code if they ought to be read by a developing person --> **its not guaranteed to be seen**. Instead write us / me directly! 

**Important**:
This branch is out of date with **feature/Issue134** which its based on. 
Because this branch was merged into main already merging this **branch into feature/Issue134** is not recommend / requires us to merge this branch once again. 

I therefore changed the **target-branch to main**. 

**However this requires** _merging_ the newest version of **feature/issue134** into this branch. 

Once this happened, you will have to resolve the mentioned merge conflicts which come from: 

- the npc_interaction refactor ( you questioned in the code, **please adapt your implementation to it!**
- the new overworld and its redesign ( also the redesigned test_overworld) 
- minor changes in the player scene ( you removed visibility of some aspects, you can leave them in during your merge ) 

**After** adapting / resolving my comments and also **merging** the newest version of feature/Issue134 into this branch we can continue merging this into **main**!

Thanks a lot

2024-01-05 20:33 UTC, ScatteredDrifter commented on Arch-enemies/singleton_scripts/singleton_player.gd
> -var npc_talked_to: Array = [0]
why delete it ? Where is this value stored afterwards? 
Its necessary so that one can solve quests that require people to talk to an npc

2024-01-05 20:33 UTC, ScatteredDrifter commented on Arch-enemies/singleton_scripts/singleton_player.gd
> +	dialogue.enter_dialogue(dialogue_data)
nice, looks good :)

2024-01-05 20:33 UTC, ScatteredDrifter commented on Arch-enemies/overworld/entities/interaction_overworld/npc_interaction.gd
> +# not fully implemented your NPC_interaction, i don't see the necessarity yet
It has been merged already and is primarily used to refactor the code and have **npc_interaction** apart from the core functionality of an NPC.

2024-01-05 20:33 UTC, ScatteredDrifter commented on Arch-enemies/overworld/entities/interaction_overworld/npc_interaction.gd
> +# @Evelyn: check_quest_condition contains the new finished condition, where do you actually update is_recruited = true?
**please** dont text over code, Its not obvious / guaranteed to be seen! 

This value ( named differently in the newest change ) is stored in the NPC Class now!

2024-01-05 20:33 UTC, ScatteredDrifter commented on Arch-enemies/overworld/entities/interaction_overworld/npc_interaction.gd
> +# how? the message might be to long to display, see example dialogue
considering that your new interaction system gets rid of it, yes its not necessary anymore. 
It was primarily used / done to have a _currently working_  dialogue foundation. Its fine if this gets replaced and deleted by the actual dialogue implementation

2024-01-05 20:33 UTC, ScatteredDrifter commented on Arch-enemies/overworld/entities/Player/Player.gd
> +	if SingletonPlayer.dialogue.in_dialogue():
reasonable, maybe it can be refactored to a method `navigation_in_dialogue()` or similar?

2024-01-05 20:33 UTC, ScatteredDrifter commented on Arch-enemies/overworld/entities/Player/Player.gd
> +				if Dialogue_Registry.npc_dialogues.has(interaction_data["npc_id"]):
ah this makes sense nice. 
However I would say that this **information** should be stored in the singleton as it represents **the player and its state**

2024-01-05 20:33 UTC, ScatteredDrifter commented on Arch-enemies/overworld/entities/Player/Player.gd
> +				# EVELYN, is this my fault that the interaction labels don't update anymore?
please dont write it here but message me directly! 

Likely because you are not passing the **dialogue-text** via the "interaction_data" Dictionary anymore?

2024-01-05 20:33 UTC, ScatteredDrifter commented on Arch-enemies/overworld/dialogue/Dialogue_Registry.gd
> +static var npc_dialogues = {1: ExampleData.new()}
might be better off stored in **singleton_player** as this is tracking / saving states?

2024-01-11 10:00 UTC, ScatteredDrifter commented
should and will resolve #188 once its done

2024-01-14 18:50 UTC, DerSimi commented on Arch-enemies/singleton_scripts/singleton_player.gd
> -var npc_talked_to: Array = [0]
I removed it.  According to my understanding, talking to an npc always insolves a dialogue, right?
There is a another representation, "finished", in the next commit, there will be an helper function in the player singleton file.

2024-01-14 21:15 UTC, DerSimi commented
killed the pull request with the last commit, I'm creating a new one to make things easier for me

2024-01-14 21:15 UTC, closed without merging