Issue172/bridge inventory
mango-gremlin/arch-enemies pull request #241
Opened 2024-01-07 20:09 UTC by Raining-Cloud

## Motivation
closes #172 

Implements a basic inventory behavior with animals for the bridge building linked to the global inventory provided by @ScatteredDrifter.
Also found a bug which caused the grid.tscn Node getting uneccesarry duplicated.

## What was changed/added
Added new variables to the grid. for the revert option. And a new condition in the grid_drag.gd checking if we have enough animals

## Testing

https://github.com/mango-gremlin/arch-enemies/assets/59502349/5c718afe-ad1f-4e25-9993-8e57e747d469

If you wan't to test this locally I suggest adding this code into the `_ready()` function in grid.gd

```
	SingletonPlayer.add_to_animal_inventory(Animal.AnimalType.DEER, 2)
	SingletonPlayer.add_to_animal_inventory(Animal.AnimalType.SNAKE, 2)
	
	start_animals = SingletonPlayer.get_animal_inventory().duplicate(true)
```

## Additional Information
We might need to be careful if we exit the bridge building, due to currently we do not reset the animal inventory count!

2024-01-07 20:23 UTC, ScatteredDrifter commented on Arch-enemies/bridges/script/grid.gd
> +			SingletonPlayer.add_to_animal_inventory(Animal.AnimalType.DEER, -1)
wouldn't it be more beneficial if this update only occurs whenever the scene is left? 

Meaning that whenever you leave the current bridge scene it propagates its inventory back to the singleton ( and update the amount of animals available based on the local inventory you copied before)

2024-01-07 20:27 UTC, ScatteredDrifter commented on Arch-enemies/singleton_scripts/singleton_player.gd
> +func add_to_animal_inventory(new_animal:Animal.AnimalType, quantity:int = 1):
reasonable change, thanks :)

2024-01-07 20:42 UTC, Kabooni requested changes
From what I've seen, it works great! 
But having another container for the inventory count is bloating our main node tree, is it possible to combine all inventory-related stuff into one separate scene? Or at least combine as much as possible?
And it would be nice if you could improve the visual design a bit more. In detail, the animal counts should align with their respective animals, and the whole inventory should be at the bottom. In the end, we want to achieve something like this:
![grafik](https://github.com/mango-gremlin/arch-enemies/assets/57258671/cbff9491-e2a1-4dc0-806c-36d9074b1ca2)
Of course, you don't have to draw anything, but everything should be in the right place to make it easier for the future. If it looks completely terrible for now or there isn't enough space, just let me know.

2024-01-07 20:42 UTC, Kabooni commented on Arch-enemies/bridges/script/grid.gd
> +			SingletonPlayer.add_to_animal_inventory(Animal.AnimalType.DEER, -1)
All this repetitive code should be refactored into a function, like e.g. remove_from_inventory(Animal.AnimalType)

2024-01-12 10:04 UTC, Raining-Cloud commented on Arch-enemies/bridges/script/grid.gd
> +			SingletonPlayer.add_to_animal_inventory(Animal.AnimalType.DEER, -1)
Yeah it would be better, but the only solution for this would be to intriduce another singleton which handles the brige inventory which I tried to avoid

2024-01-12 11:23 UTC, Kabooni commented on Arch-enemies/bridges/script/grid.gd
> +			SingletonPlayer.add_to_animal_inventory(Animal.AnimalType.DEER, -1)
Part of the issue description was to find a way to handle everything _without_ having to edit the player singleton all the time, and if you need another singleton for that, it's fine.
I mean you could just use grid.gd or the animal count labels as a "local" singleton and create an inventory dictionary as suggested in the issue. When clicking the return button in the goal menu, you could signal that to grid.gd and change the player singleton based on the inventory.

2024-01-12 11:33 UTC, Kabooni commented on Arch-enemies/bridges/script/grid.gd
> +			SingletonPlayer.add_to_animal_inventory(Animal.AnimalType.DEER, -1)
Even repositioning the inventory and aligning the labels?

2024-01-12 11:50 UTC, Kabooni commented on Arch-enemies/bridges/script/grid.gd
> +			SingletonPlayer.add_to_animal_inventory(Animal.AnimalType.DEER, -1)
Additionally, it would make it much easier to export the inventory. We need an easier way to change the inventory values for testing purposes, rather than having to change the code.

2024-01-12 14:49 UTC, Raining-Cloud commented on Arch-enemies/bridges/script/grid.gd
> +			SingletonPlayer.add_to_animal_inventory(Animal.AnimalType.DEER, -1)
Ok it seems that you can move the animals, this is implemented statically so I will give it a shot. the align is probably easy, I just need to check how GoDot UI works

2024-01-12 15:44 UTC, Kabooni commented on Arch-enemies/bridges/script/grid.gd
> +			SingletonPlayer.add_to_animal_inventory(Animal.AnimalType.DEER, -1)
Or in worst case scenario remove just the label container and align the labels separately

2024-01-13 00:18 UTC, ScatteredDrifter commented on Arch-enemies/bridges/script/grid.gd
> +			SingletonPlayer.add_to_animal_inventory(Animal.AnimalType.DEER, -1)
> and if you need another singleton for that, it's fine. 

Tbh I disagree, A singletone would be loaded constantly and persist even if the bridge-scene ( and therefore its required context ) is left / terminated

2024-01-13 10:32 UTC, koennixer approved these changes
Many of the issues raised above are valid. What I would like to caution is that this change is behind the current main significantly. Many of the previous bugs and code smells are still here. The inventory it self, for just its own works.

The issues currently being discussed, as far as I can tell, is how to handle singleton values and also the positioning and appearance of the animals. These are, in my mind, completely separate issues that can be solved separate of just this inventory issue. Specifically making the position of the sprites not hard coded is something that can solved it's own issues and is a major point of contention here. I would prefer it if we got around to merging this soon and then address the other problems in their own issues to avoid this code falling even further behind. Any remaining oddities, like the handling of singletons, can be fixed in a refactoring at the end when we know the full scope of what we need to handle globally.

2024-01-13 14:20 UTC, mango-gremlin requested changes
So I agree with all three of you here on separate things
- we agreed on not refactoring for now, so this should be left out of this pr. However it would be nice if you tried to write code that doesnt need to be refactored in the first place, as code quality is important.
- positioning of animals was not something that was part of the issue. So there should be a separate issue for this
- HOWEVER: currently the singleton is being edited the entire time, as far as I understand? This is specifically something that the issue mentioned not to do. I did say this was okay, so thats my mistake. But i just thought about it again and what happens if you leave the bridge level? Then it doesnt save your animals in the bridge level (this is not a feature that will be included in the final game) - so you just lose animals? this shouldnt happen. Of course you could just reset everything - performance wise it shouldnt matter- but thats really smelly. So you should save the amount of each animal in a separate data structure. And edit this separate data structure. Only interact with the singleton when querying the animal amounts at the beginning, and when the level is solved to update the animal amounts.

2024-01-13 14:29 UTC, ScatteredDrifter commented on Arch-enemies/bridges/script/grid.gd
> +			SingletonPlayer.add_to_animal_inventory(Animal.AnimalType.DEER, -1)
> Ok it seems that you can move the animals, this is implemented statically so I will give it a shot. the align is probably easy, I just need to check how GoDot UI works

I would argue that this implementation does not have to implement the UI-elements correctly. 
-> Primarily because this is mostly a design choice and should therefore be handled by the ui/assets team ? 

Of course, to implement the UI it requires the base functionality ( i.e having an inventory that updates accordingly and can be queried ) however I would say that the actual implementation of the ui should be resolved in a separate branch or at least not solely by the person doing the back-end. In other words the ui-assets might be required to take a look and add it too ( at best together in person or remotely ^^)

2024-01-13 15:01 UTC, Kabooni approved these changes
Alright I see all your points. The code works of course, so after @mango-gremlin's request was implemented we can merge it and do everything else later.

2024-01-13 23:57 UTC, ScatteredDrifter commented
Changes to convert to a local inventory were incorporated in #262 .
The branch should be used as it contains newer changes, is up to date with main and satisfies the requirements. 

Closing this PR is advised, as its superseded by #262

2024-01-15 08:41 UTC, closed without merging

2024-01-15 08:41 UTC, ScatteredDrifter commented
**\\** closed as #262  provides the more up to date version of this feature **//**