bridges | Fixed boundary issues
mango-gremlin/arch-enemies pull request #244
Opened 2024-01-08 22:35 UTC by koennixer

## Motivation
closes #214

When dragging the cursor to the edge it could crash the game because wrong array elements might be accessed.

## What was changed/added
An out_of_bounds function was added that checks if the current cursor position would check an illegal square for the current
animal. This is based on the animals sprite size (which is very handy to implement for other animals).

## Testing

https://github.com/mango-gremlin/arch-enemies/assets/65815628/c3b5a870-7528-42f1-a6ad-6a26e4834f1b

2024-01-08 22:54 UTC, Kabooni requested changes
Now I can't place anything anymore. I'll update the comment after I find the cause, should I be faster than you.
Update: Something is very wrong with out_of_bound(), it's basically always true.

2024-01-08 23:33 UTC, koennixer commented
I made it actually work now. Sorry, should have tested more extensively.

2024-01-08 23:46 UTC, marcel-iv requested changes
I still found some minor bugs:
- placing an animal in the leftmost square is impossible
- placing an animal in the rightmost square is impossible

Another thing to consider is that sometimes, you might want to place an animal slightly outside the screen (lets say the leftmost part of the animal would be outside the grid). I think its more intuitive to allow these types of placement. However, this is relevant to a different part of the code and probably unreasonable to do until tomorrow. 

We can merge once the bugs above have been adressed.

2024-01-08 23:53 UTC, Kabooni approved these changes
It works now, but you can't drag a deer into shallow water anymore. But this bug is known and will be addressed elsewhere.

2024-01-09 00:01 UTC, Kabooni commented
> I still found some minor bugs:
> 
>     * placing an animal in the leftmost square is impossible
> 
>     * placing an animal in the rightmost square is impossible
> 
> 
> Another thing to consider is that sometimes, you might want to place an animal slightly outside the screen (lets say the leftmost part of the animal would be outside the grid). I think its more intuitive to allow these types of placement. However, this is relevant to a different part of the code and probably unreasonable to do until tomorrow.
> 
> We can merge once the bugs above have been adressed.

We could just increase the grid size by two squares, but leave the viewport size as it is. Then it should theoretically be possible to place an animal slightly "outside" the window, but it would also make it possible to place e.g. a spider completely outside. It's not a perfect fix, but I think enough for tomorrow.

2024-01-09 00:05 UTC, koennixer commented
> I still found some minor bugs:
> 
> * placing an animal in the leftmost square is impossible
> * placing an animal in the rightmost square is impossible

This is more a simplification that it is a bug. Most animals have square around it with tiles that are to be allowed or forbidden, i.e. the snakes head. If you account for all these possibilities it makes the function extremely bloated and much less intuitive. Personally I feel like the ability to place in these squares, which will be hardly relevant, is not really worth it.

2024-01-09 00:05 UTC, marcel-iv commented
> We could just increase the grid size by two squares, but leave the viewport size as it is. Then it should theoretically be possible to place an animal slightly "outside" the window, but it would also make it possible to place e.g. a spider completely outside. It's not a perfect fix, but I think enough for tomorrow.

Thats actually a really good idea, although a bit hacky for my taste. Should be enough for the presentation, although I think the current implementation is sufficient already. Additionally, we should really think about getting the grid size automatically, the current solution isn't great.

2024-01-09 00:32 UTC, marcel-iv approved these changes
In that case, we can merge now, and implement a slightly more dynamic system that allows placement on the sides of the grid on a later date

2024-01-09 00:49 UTC, merged