bridges | disable all actions when menus are open
mango-gremlin/arch-enemies pull request #278
Opened 2024-01-16 23:20 UTC by aylinfi

## Motivation
closes #272 

All actions where still fully functional when the pause or goal menu was open. They should be paused/disabled instead.

## What was changed/added
Added global variables to keep track of when menus are open and changed functions to be dependent on these variables.
Also wrote new global function to change visibility of all ui elements which also disables them when invisible.

## Testing

https://github.com/mango-gremlin/arch-enemies/assets/116217918/8b8cde02-88a7-4ce1-a6b8-cae678a56fad

## Additional Information
Remind me to add similar functionalities to overworld menu.

2024-01-16 23:27 UTC, mango-gremlin requested changes
this looks great, but maybe we should refrain from further using the global script, as it is kind of bad practice to use this kind of thing? Instead maybe we could save it in the singleton, in which case the same stuff can also be used for disabling movement when in the menu in the overworld. Btw, is this something that you implemented here as well? Because it should also work in the overworld in the same way with disabling movement.

2024-01-16 23:33 UTC, ScatteredDrifter reviewed
ran through your changes and made some minor annotations. Maybe you could answer / go over them. 

Other than that your changes seem reasonable :)

2024-01-16 23:33 UTC, ScatteredDrifter commented on Arch-enemies/singleton_scripts/singleton_player.gd
> +	inventory[Animal.AnimalType.DEER] = 5
this shouldn't be changed ( normally )

2024-01-16 23:33 UTC, ScatteredDrifter commented on Arch-enemies/overworld/ui/menu/menu/pause_menu.gd
> +	Global.drag_mode = true
wouldn't it be beneficial if we extracted that to some method? 
something like:
```
reset_global_bridge_state(state:bool)
	Global.drag_mode = true
	Global.menu_mode = state
	Global.goal_reached = state
```

2024-01-16 23:33 UTC, ScatteredDrifter commented on Arch-enemies/overworld/ui/menu/menu/pause_menu.gd
> +	Global.drag_mode = true
( would reduce the amount of ducplicated code and make it easier to read )

2024-01-16 23:33 UTC, ScatteredDrifter commented on Arch-enemies/bridges/script/toggle_mode_button.gd
> +# FIXME "res://bridges/scenes/toggle_build_fox_mode.gd" replaces this skript
maybe remove it ( or is there to provide information afterwards? )

2024-01-16 23:33 UTC, ScatteredDrifter commented on Arch-enemies/bridges/script/player.gd
> +	if not Global.menu_mode:
we could use less indentation by inverting this condition 
```
 if Global.menu_mode:
     return
```
might make it easier to read :)

2024-01-16 23:33 UTC, ScatteredDrifter commented on Arch-enemies/bridges/script/goal_menu.gd
> +	Global.menu_mode = false
would once again advise extracting this in a separate method as denoted below

2024-01-17 10:08 UTC, ScatteredDrifter commented on Arch-enemies/singleton_scripts/singleton_player.gd
> +	inventory[Animal.AnimalType.DEER] = 5
considering that its for testing purposes only and that we require some animals to test a level, thats fine  //

2024-01-20 16:16 UTC, aylinfi commented
There is an error when reaching the goal and pressing continue, but this is related to bridge_connections/edges which I am not at all familiar with.

2024-01-20 16:24 UTC, Kabooni commented
> There is an error when reaching the goal and pressing continue, but this is related to bridge_connections/edges which I am not at all familiar with.

Did you test it while directly starting in grid.tscn? As the levels are now connected to the main overworld, you need to start there and enter the level for the bridge_edge to be set correctly. Without doing that, the level doesn't know its own bridge edge.

2024-01-20 16:48 UTC, ScatteredDrifter requested changes
thx for updating this repo. 
The menu does not work in the overworld as it tries to query the method "reset_modes()" from a parent, however this structure is not present when executing in the overworld.

2024-01-20 16:48 UTC, ScatteredDrifter commented on Arch-enemies/overworld/ui/menu/menu/pause_menu.gd
> +	get_parent().reset_modes()
this does not work globally! 

If I were to call execute the menu in the overworld the game crashes because its parent ( which is not grid! ) does not contain this method.

2024-01-20 16:48 UTC, ScatteredDrifter commented on Arch-enemies/bridges/script/player.gd
> +	if get_parent().menu_mode:
maybe you can query the parent once and then reference it every time. looks better regarding code quality :)

2024-01-20 16:48 UTC, ScatteredDrifter commented on Arch-enemies/bridges/script/grid.gd
> +		var pause_menu = get_parent().find_child("bridges_pause_menu")
I would once again set an \@export link to help setting this value instead of querying it relative from the node-structure. In case the hierarchy changes this would break again

2024-01-20 17:20 UTC, aylinfi commented on Arch-enemies/overworld/ui/menu/menu/pause_menu.gd
> +	get_parent().reset_modes()
i fixed this now

2024-01-21 17:01 UTC, Kabooni approved these changes
As everything left is refactoring, I would propose we merge this pr and do the refactoring later with the rest. I would love to have this feature for playtesting.

2024-01-25 12:49 UTC, ScatteredDrifter approved these changes
after you've fixed the issues described ( primarily game crashing when opening the menu in the overworld ) it works well, thanks :)

2024-01-25 14:40 UTC, mango-gremlin approved these changes
lgtm!

2024-01-25 23:18 UTC, merged